export enum ErrorType {
  AUTH_FAILED = "AUTH_FAILED",
  NETWORK_ERROR = "NETWORK_ERROR",
  RATE_LIMITED = "RATE_LIMITED",
  MALFORMED_RESPONSE = "MALFORMED_RESPONSE",
  INTERNAL_ERROR = "INTERNAL_ERROR",
}
